env: "local"

db:
  my_db_kub:
    driver: postgres
    host: localhost
    port: 5555
    user: root
    password: passw0rd
    database: ludwig_the_holy_blade
  eiei_db:
    driver: mysql
    host: localhost
    port: 6666
    user: root
    password: passw0rd
    database: eiei

log:
  level: "info"
  json_format: false
  show_body: true
  show_body_on_error: true
  pretty: true
  include_health: false

http:
  max_idle_conns: 100
  max_conns_per_host: 100
  max_idle_conns_per_host: 100

microservice:
  timeout: "20s"
  customer_service:
    base_url: "http://localhost:8080/customers"
    endpoints:
      inq_by_cif:
        http_method: "GET"
        endpoint: "/:id"
      list:
        http_method: "GET"
        endpoint: ""

external_api:
  user_centers:
    timeout: "20s"
    certs:
      certs_require: true # true for continue to insecureSkip and certs parse
      insecure_skip: true
      certs: "secret"
    base_url: "https://localhost:8081/user_centers"
    endpoints:
      inquiry:
        http_method: "GET"
        endpoint: ""
      add:
        http_method: "POST"
        endpoint: ""

redis:
  my_rdb:
    host: "localhost"
    password: "passw0rd"
    port: 6379
    db: 0
    connection:
      default: true # default conn pool setting by redis lib
      max_retries: 3
      min_retry_backoff: "8ms"
      max_retry_backoff: "512ms"
      dial_timeout: "5s"
      read_timeout: "3s"
      write_timeout: "3s"
      pool_size: 10
      min_idle_conns: 0
      max_conn_age: ""
      pool_timeout: "4s"
      idle_timeout: "5m"
      idle_check_frequency: "1m"
    expiration_config:
      inq_user: "15m"

  my_other_rdb:
    host: "localhost"
    password: "passw0rd"
    port: 6380
    db: 0
    connection:
      default: true
      max_retries: 3
      min_retry_backoff: "8ms"
      max_retry_backoff: "512ms"
      dial_timeout: "5s"
      read_timeout: "3s"
      write_timeout: "3s"
      pool_size: 10
      min_idle_conns: 0
      max_conn_age: ""
      pool_timeout: "4s"
      idle_timeout: "5m"
      idle_check_frequency: "1m"
    expiration_config:
      something: "15m"